config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, :only => [:show, :index]

  root "pages#home"

  resources :articles do
    get 'change_privacy', on: :member

    resources :contributors, :only => [:index, :destroy] do
      get 'add_contributor_to_article', on: :member
    end

    resources :article_bodies, :except => [:index] do
      get 'make_stable', on: :member
    end

    resources :comments, :only => [:index, :create, :destroy] do
      resources :sub_comments, :only => [:new, :create, :destroy]
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: { minimum: 2, maximum: 500 }

  has_many :sub_comments, dependent: :destroy
  belongs_to :article
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article
  before_action :private_article

  def index
    @comments = @article.comments.paginate(page: params[:page], per_page: 7)
    @comment = current_user.comments.new
  end

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.article = @article
    if @comment.save
      flash[:notice] = "Comment published"
      redirect_to article_comments_path(@article)
    else
      flash[:alert] = "Failed to publish comment"
      redirect_to article_path(@article)
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    unless @comment.user == current_user || @article.user == current_user
      flash[:alert] = "Only the article owner can perform this action"
      redirect_to root_path
    else
      @comment.destroy
      flash[:notice] = "Comment was successfully deleted"
      redirect_to article_comments_path(@article)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_article
    @article = Article.find(params[:article_id])
  end

  def private_article
    if @article.private && (@article.user != current_user && @article.contributors.exclude?(current_user))
      flash[:alert] = "Only the article owner or contributor can perform this action"
      redirect_to root_path
    end
  end
end

app/views/comments/_comments.html.erb
<div class="mspace">
  <% if @comments.any? %>
    <div class="offset-5">
      <%= will_paginate @comments %>
    </div>
    <% @comments.each do |comment| %>
      <div class="card border-success space col-sm-12 col-lg-8">
        <div class="card-body">
          <p class="card-title">
            <b><%= link_to comment.user.full_name, user_path(comment.user), class: "text-dark" %></b>
            -
            <%= time_ago_in_words(comment.created_at) %> ago
            <% if comment.user == @article.user %>
              <br />
              <b class="writer-comment">Article Writer</b>
            <% elsif @article.contributors.include?(comment.user)%>
              <br />
              <b class="contributor-comment">Article contributor</b>
            <% end %>
          </p>
          <p class="card-text" style="margin:0;">
            <%= comment.body %>
          </p>
          <%= link_to "Reply", new_article_comment_sub_comment_path(@article, comment),
                               class: "btn btn-success btn-sm sspace-top" %>
          <% if comment.user == current_user || @article.user == current_user %>
            <%= link_to "Delete", article_comment_path(@article, comment),
                                  method: :delete,
                                  data: {confirm: "Are you sure?"},
                                  class: "btn btn-danger btn-sm sspace-top" %>
          <% end %>
        </div>
      </div>

      <% if comment.sub_comments.any? %>
        <% comment.sub_comments.each do |sub| %>
          <div class="row">
            <div class="col-1">
              <svg width="100%" height="100%" viewBox="0 0 16 16" class="bi bi-arrow-return-right" fill="#5cb85c" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M1.5 1.5A.5.5 0 0 0 1 2v4.8a2.5 2.5 0 0 0 2.5 2.5h9.793l-3.347 3.346a.5.5 0 0 0 .708.708l4.2-4.2a.5.5 0 0 0 0-.708l-4-4a.5.5 0 0 0-.708.708L13.293 8.3H3.5A1.5 1.5 0 0 1 2 6.8V2a.5.5 0 0 0-.5-.5z"/>
              </svg>
            </div>
            <div class="card border-info space col-11 col-sm-11 col-lg-7">
              <div class="card-body">
                <p class="card-title">
                  <b><%= link_to sub.user.full_name, user_path(sub.user), class: "text-dark" %></b>
                  -
                  <%= time_ago_in_words(sub.created_at) %> ago
                  <% if sub.user == @article.user %>
                    <br />
                    <b class="writer-comment">Article Writer</b>
                  <% elsif @article.contributors.include?(sub.user)%>
                    <br />
                    <b class="contributor-comment">Article contributor</b>
                  <% end %>
                </p>
                <p class="card-text" style="margin:0;">
                  <%= sub.body %>
                </p>
                <% if sub.user == current_user || @article.user == current_user %>
                  <%= link_to "Delete", article_comment_sub_comment_path(@article, comment, sub),
                                        method: :delete,
                                        data: {confirm: "Are you sure?"},
                                        class: "btn btn-danger btn-sm sspace-top" %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  <% else %>
    <p class="danger">Still no comments to display</p>
  <% end %>
</div>

app/views/comments/_form.html.erb
<div class="space">
<%= form_for([@article, @comment]) do |f| %>
    <div class="sspace">
      <div class="row col-12">
        <b><%= f.label :body, "Comment:" %></b>
      </div>

      <div class="row col-md-8 col-lg-6">
        <%= f.text_area :body, class: "form-control" %>
      </div>
    </div>

    <div class="row col-12 mspace">
      <%= f.submit "Post", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/comments/index.html.erb
<%= render "shared/title", title: "Article discussion", subtitle: "\"#{@article.name}\" by #{@article.user.full_name}" %>

<%= render "comments" %>

<%= render "form" %>

<div>
  <p><%= link_to "Return", article_path(@article), class: "btn btn-success" %></p>
</div>