config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, :only => [:show, :index]

  root "pages#home"

  resources :articles do
    get 'change_privacy', on: :member

    resources :contributors, :only => [:index, :destroy] do
      get 'add_contributor_to_article', on: :member
    end

    resources :article_bodies, :except => [:index] do
      get 'make_stable', on: :member
    end

    resources :comments, :only => [:index, :create, :destroy] do
      resources :sub_comments, :only => [:new, :create, :destroy]
    end
  end
end

app/models/article.rb
class Article < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { minimum: 4, maximum: 40 }
  validates :user_id, presence: true

  default_scope -> { order(created_at: :desc) }

  belongs_to :user
  has_many :article_bodies, dependent: :destroy
  has_many :contributions, dependent: :destroy
  has_many :contributors, through: :contributions, class_name: "User"
  has_many :comments, dependent: :destroy
  has_many :sub_comments, dependent: :destroy
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  require "will_paginate/array"
  before_action :authenticate_user!
  before_action :set_article, except: [:new, :create, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy, :change_privacy]

  def new
    @article = current_user.articles.new
  end

  def create
    @article = current_user.articles.new(article_params)
    if @article.save
      flash[:notice] = "Article has been created"
      redirect_to article_path(@article)
    else
      flash[:alert] = "Failed to create article"
      render "new"
    end
  end

  def edit; end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article has been updated"
      redirect_to article_path(@article)
    else
      flash[:alert] = "Failed to updated article"
      render "new"
    end
  end

  def index
    @articles = Article.all.select { |article|
      article.user == current_user || article.contributors.include?(current_user) || !article.private
    }.paginate(page: params[:page], per_page: 5)
  end

  def show
    if @article.private && (@article.user != current_user && @article.contributors.exclude?(current_user))
      flash[:alert] = "Only the article owner or contributor can perform this action"
      redirect_to root_path
    end

    @contributors = @article.contributors.paginate(page: params[:page], per_page: 5)

    @article_bodies = @article.article_bodies.paginate(page: params[:page], per_page: 5)

    stable = @article.article_bodies.where(stable_version: true).first
    if stable
      @stable_body_version = stable
    else
      @stable_body_version = @article.article_bodies.first
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = "Article was successfully deleted"
    redirect_to articles_path
  end

  def change_privacy
    ArticlePrivacy.new(@article).toggle_privacy
    flash[:notice] = "Article privacy updated"
    redirect_to article_path(@article)
  end

  private

  def article_params
    params.require(:article).permit(:name, :user_id, :private)
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def require_same_user
    if @article.user != current_user
      flash[:alert] = "Only the article owner can perform this action"
      redirect_to root_path
    end
  end
end

app/views/articles/_article_body_options.html.erb
<% if @article.user == current_user || @contributors.include?(current_user) %>
  <% if @article_bodies.any? %>
    <div class="sspace">
      <h5>Article body options:</h5>
    </div>
    <div class="space">
      <%= link_to "Create a new version from this one", edit_article_article_body_path(@article, @stable_body_version),
                                                        class: "btn btn-sm btn-success" %>

      <% if @article.user == current_user %>
        <u><%= link_to "Delete version", article_article_body_path(@article, @stable_body_version),
                                         method: :delete,
                                         data: {confirm: "Are you sure?"},
                                         class: "btn btn-sm btn-danger" %></u>
      <% end %>
    </div>
  <% else %>
    <div class="sspace">
      <h5>Article body options:</h5>
    </div>
    <div class="space">
      <%= link_to "Create article body", new_article_article_body_path(@article),
                                         class: "btn btn-sm btn-success" %>
    </div>
  <% end %>
<% end %>

app/views/articles/_article_body_text.html.erb
<% if @article_bodies.any? %>
  <div class="mspace">
    <p class="space"><%= @stable_body_version.body %></p>
    <p class="small sspace"><b>
      Article created on <%= @article.created_at.strftime("%d/%m/%Y at %I:%M%p") %>
      <br />
      Article creator: <%= link_to @article.user.full_name, user_path(@article.user), class: "text-dark" %>
      <br />
      Body version: <%= @stable_body_version.version %>
      <br />
      Version writer: <%= @stable_body_version.updater %>
      <br />
      Version created on: <%= @stable_body_version.created_at.strftime("%d/%m/%Y at %I:%M%p") %>
      <br />
      <% if @article.user == current_user || @contributors.include?(current_user) %>
        Visibility:
        <% if @article.private == false %>
          <span class="success">Public</span>
        <% else %>
          <span class="danger">Private</span>
        <% end %>
      <% end %>
    </b></p>

    <% if @stable_body_version.stable_version %>
      <p class="small success"><b>
        Stable body version
      </b></p>
    <% else %>
      <p class="small danger" style="margin:0;"><b>
        Latest body version (no stable version yet)
      </b></p>
      <% if @article.user == current_user %>
        <%= link_to "Make version stable", [:make_stable, @article, @stable_body_version], class: "btn btn-sm btn-success" %>
      <% end %>
    <% end %>
  </div>
<% else %>
  <p class="space danger"><b>Body hasn't been created</b></p>
  <p class="small mspace"><b>
    Article created on <%= @article.created_at.strftime("%d/%m/%Y at %I:%M%p") %>
    <br />
    Article creator: <%= link_to @article.user.full_name, user_path(@article.user), class: "text-dark" %>
    <br />
    <% if @article.user == current_user || @contributors.include?(current_user) %>
      Visibility:
      <% if @article.private == false %>
        <span class="success">Public</span>
      <% else %>
        <span class="danger">Private</span>
      <% end %>
    <% end %>
  </b></p>
<% end %>

app/views/articles/_article_options.html.erb
<% if @article.user == current_user %>
  <div class="sspace">
    <h5>Article options:</h5>
  </div>
  <div class="space">
    <%= link_to "Edit title", edit_article_path(@article), class: "btn btn-sm btn-success" %>
    <%= link_to "Change visibility", [:change_privacy, @article], data: {confirm: "Are you sure?"},
                                                                  class: "btn btn-sm btn-success" %>
    <%= link_to "Delete article", article_path(@article),
                                  method: :delete,
                                  data: {confirm: "Are you sure?"},
                                  class: "btn btn-sm btn-danger" %>
  </div>
<% end %>

app/views/articles/_contributors.html.erb
<div class="mspace">
  <h5>Contributors:</h5>
  <% if @article.user == current_user %>
    <div class="sspace">
      <%= link_to "Add contributors", article_contributors_path(@article), class: "btn btn-sm btn-success" %>
    </div>
  <% end %>
  <% if @contributors.any? %>
    <div>
      <%= will_paginate @contributors %>
    </div>
      <% @contributors.each do |contributor| %>
        <div class="sspace card border-dark col-12 col-sm-10 col-md-8 col-lg-6">
          <p style="margin:0;"><u><%= link_to contributor.full_name, user_path(contributor), class: "text-dark" %></u>
          <% if @article.user == current_user || contributor == current_user %>
            &nbsp; - &nbsp;
            <%= link_to "Remove", article_contributor_path(@article, contributor),
                                  method: :delete,
                                  data: {confirm: "Are you sure?"},
                                  class: "danger" %>
          <% end %>
          </p>
        </div>
      <% end %>

  <% else %>
    <p class="danger"><b>No contributors yet</b></p>
  <% end %>
</div>

app/views/articles/edit.html.erb
<%= render "shared/title", title: "Edit Title", subtitle: "" %>

<%= render "shared/errors", obj: @article %>
<!-- Form -->
<div class="xspace">
  <%= form_for @article do |f| %>
    <div class="space space-top">
      <div class="row col-12">
        <b><%= f.label :name %></b>
      </div>

      <div class="row col-md-8 col-lg-6">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>

    <div class="row col-12">
      <%= f.submit "Confirm", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

<div>
  <%= link_to "Return", article_path(@article), class: "btn btn-success" %>
</div>

app/views/articles/index.html.erb
<%= render "shared/title", title: "Articles", subtitle: "" %>

<div>
  <%= link_to "New Article", new_article_path, class: "btn btn-success mspace" %>
</div>

<div class="offset-5">
  <%= will_paginate @articles %>
</div>

<% @articles.each do |article| %>
  <div class="card border-success space col-sm-12 col-lg-8">
    <div class="card-body">
      <h5>
        <u><%= link_to article.name, article_path(article), class: "text-dark" %></u>
      </h5>
      <p style="margin:0;">
        Author: <u><%= link_to article.user.full_name, user_path(article.user), class: "text-dark" %></u>
        <br />
        Date: <%= article.created_at.strftime("%d/%m/%Y") %>
      </p>
      <% if article.user == current_user %>
        <%= link_to "Delete article", article_path(article),
                                      method: :delete,
                                      data: {confirm: "Are you sure?"},
                                      class: "btn btn-danger btn-sm sspace-top" %>
      <% end %>
    </div>
  </div>
<% end %>

<div>
  <%= link_to "Return", root_path, class: "btn btn-success" %>
</div>

app/views/articles/new.html.erb
<%= render "shared/title", title: "Create New Article", subtitle: "" %>

<%= render "shared/errors", obj: @article %>
<!-- Form -->
<div class="xspace">
  <%= form_for @article do |f| %>
    <div class="space space-top">
      <div class="row col-12">
        <b><%= f.label :name %></b>
      </div>
      <div class="row col-md-8 col-lg-6">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>

    <div class="space">
      <div class="col-12 row">
        <div class="privaci-icon">
          <%= f.radio_button :private, false, :checked => true %>
          <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-book-half" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M8.5 2.687v9.746c.935-.53 2.12-.603 3.213-.493 1.18.12 2.37.461 3.287.811V2.828c-.885-.37-2.154-.769-3.388-.893-1.33-.134-2.458.063-3.112.752zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"/>
          </svg>
        </div>

        <div>
          <p><b><%= label :private_true, "Public" %></b></p>
          <p class="small privaci-description">All user will be able to see it</p>
        </div>
      </div>

      <div class="col-12 row">
        <div class="privaci-icon">
          <%= f.radio_button :private, true %>

          <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-lock-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path d="M2.5 9a2 2 0 0 1 2-2h7a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-7a2 2 0 0 1-2-2V9z"/>
            <path fill-rule="evenodd" d="M4.5 4a3.5 3.5 0 1 1 7 0v3h-1V4a2.5 2.5 0 0 0-5 0v3h-1V4z"/>
          </svg>
        </div>

        <div>
          <p><b><%= label :private_false, "Private" %></b></p>
          <p class="small privaci-description">Visibility is restricted to you and contributors</p>
        </div>
      </div>
    </div>

    <div class="row col-12">
      <%= f.submit "Confirm", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

<div>
  <%= link_to "Return", articles_path, class: "btn btn-success" %>
</div>

app/views/articles/show.html.erb
<%= render "shared/title", title: @article.name, subtitle: "" %>

<%= render "article_body_text" %>

<%= render "article_options" %>

<%= render "article_body_options" %>

<% if @article_bodies.count > 1 %>
  <div class="space">
    <h5>All body versions:</h5>
    <div>
      <%= will_paginate @article_bodies %>
    </div>
    <% @article_bodies.each do |body| %>
      <div class="card sspace border-dark col-12 col-sm-11 col-md-8 col-lg-6">
        <p style="margin:0;"><%= link_to "Version: #{body.version} -
          Created on: #{body.created_at.strftime("%d/%m/%Y at %I:%M%p")}",
          article_article_body_path(@article, body), class: "text-dark" %>
          <% if body.stable_version %>
            &nbsp;<b class="success">Stable</b>
          <% end %>
        </p>
      </div>
    <% end %>
  </div>
<% end %>

<%= render "contributors" %>

<div class="mspace">
  <%= link_to "Article discussion", article_comments_path(@article), class: "btn btn-warning" %>
</div>

<div>
  <p><%= link_to "Return to articles index", articles_path, class: "btn btn-success" %></p>
  <p><%= link_to "Return to your articles", user_path(current_user), class: "btn btn-success" %></p>
</div>