config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, :only => [:show, :index]

  root "pages#home"

  resources :articles do
    get 'change_privacy', on: :member

    resources :contributors, :only => [:index, :destroy] do
      get 'add_contributor_to_article', on: :member
    end

    resources :article_bodies, :except => [:index] do
      get 'make_stable', on: :member
    end

    resources :comments, :only => [:index, :create, :destroy] do
      resources :sub_comments, :only => [:new, :create, :destroy]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :last_name, presence: true, length: { minimum: 2, maximum: 20 }

  has_many :articles, dependent: :destroy
  has_many :contributions, dependent: :destroy
  has_many :collaborations, through: :contributions, class_name: "Article"
  has_many :comments, dependent: :destroy
  has_many :sub_comments, dependent: :destroy

  default_scope -> { order(created_at: :desc) }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require "will_paginate/array"
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])

    @articles = @user.articles.select { |article|
      article.user == current_user  || article.contributors.include?(current_user) || !article.private
    }.paginate(page: params[:articles_page], per_page: 5)

    @contributions = @user.collaborations.select { |article|
      article.user == current_user  || article.contributors.include?(current_user) || !article.private
    }.paginate(page: params[:contributions_page], per_page: 5)
  end

  def index
    @users = User.all.paginate(page: params[:page], per_page: 5)
  end
end

app/views/users/index.html.erb
<%= render "shared/title", title: "Users", subtitle: "" %>

<div class="offset-4 offset-md-5 space">
  <%= will_paginate @articles %>
</div>

<% @users.each do |user| %>
  <div class="card border-success space col-sm-12 col-lg-8">
    <div class="card-body">
      <h5 class="card-title">
        <u><%= link_to user.full_name, user_path(user), class: "text-dark" %></u>
      </h5>
      <p class="card-text">
        Number of articles: <%= user.articles.count %>
        <br />
        Number of contributions: <%= user.collaborations.count %>
        <br />
        Signed in: <%= user.created_at.strftime("%d/%m/%Y") %>
      </p>
    </div>
  </div>
<% end %>

<div>
  <%= link_to "Return", root_path, class: "btn btn-success" %>
</div>

app/views/users/show.html.erb
<%= render "shared/title", title: "#{@user.first_name} info", subtitle: "" %>

<div class="mspace">
  <p>
    Name: <b><%= @user.full_name %></b>
    <br />
    Number of articles: <%= @user.articles.count %>
    <br />
    Number of contributions: <%= @user.contributions.count %>
    <br />
    Signed in: <%= @user.created_at.strftime("%d/%m/%Y") %>
  </p>
</div>

<div class="space">
  <h4>Articles:</h4>
</div>

<div class="offset-5">
  <%= will_paginate @articles, :param_name => "articles_page" %>
</div>

<% if @articles.any? %>
  <% if @user == current_user %>
    <%= link_to "New Article", new_article_path, class: "btn btn-success mspace" %>
  <% end %>
  <% @articles.each do |article| %>
  <div class="card border-success space col-sm-12 col-lg-8">
      <div class="card-body">
        <h5>
          <u><%= link_to article.name, article_path(article), class: "text-dark" %></u>
        </h5>
        <p>Date: <u><%= article.created_at.strftime("%d/%m/%Y") %></u></p>
        <% if article.user == current_user %>
          <u><%= link_to "Delete article", article_path(article),
                                           method: :delete,
                                           data: {confirm: "Are you sure?"},
                                           class: "btn btn-danger btn-sm" %></u>
        <% end %>
      </div>
    </div>
  <% end %>
<% else %>
  <% if @user == current_user %>
    <%= link_to "New Article", new_article_path, class: "btn btn-success mspace" %>
  <% end %>
  <div class="mspace danger">
    <h5>Still no articles to display</h5>
  </div>
<% end %>

<div class="space">
  <h4>Contributions:</h4>
</div>

<div class="offset-5">
  <%= will_paginate @contributions, :param_name => "contributions_page" %>
</div>

<% if @contributions.any? %>
  <% @contributions.each do |article| %>
    <div class="card border-success space col-sm-12 col-lg-8">
      <div class="card-body">
        <h5>
          <u><%= link_to article.name, article_path(article), class: "text-dark" %></u>
        </h5>
        <p>
          Author: <u><%= link_to article.user.full_name, user_path(article.user), class: "text-dark" %></u>
          <br />
          Date: <u><%= article.created_at.strftime("%d/%m/%Y") %></u>
        </p>
        <% if article.user == current_user || @user == current_user %>
          <u><%= link_to "Remove", article_contributor_path(article, @user),
                                   method: :delete,
                                   data: {confirm: "Are you sure?"},
                                   class: "btn btn-danger btn-sm" %></u>
        <% end %>
      </div>
    </div>
<% end %>
<% else %>
  <div class="mspace danger">
    <h5>No contributions to display</h5>
  </div>
<% end %>

<div>
  <%= link_to "Return", users_path, class: "btn btn-success" %>
</div>