config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, :only => [:show, :index]

  root "pages#home"

  resources :articles do
    get 'change_privacy', on: :member

    resources :contributors, :only => [:index, :destroy] do
      get 'add_contributor_to_article', on: :member
    end

    resources :article_bodies, :except => [:index] do
      get 'make_stable', on: :member
    end

    resources :comments, :only => [:index, :create, :destroy] do
      resources :sub_comments, :only => [:new, :create, :destroy]
    end
  end
end

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="mspace">
    <div class="col-12">
      <div class="card border-danger">
        <div class="card-header text-danger">
          <h4>
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this from behing saved:
          </h4>
          </div>
          <div class="card-body text-danger">
          <% obj.errors.full_messages.each do |msg| %>
            <ul>
              <li><%= msg %></li>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer space-top">
  <div class="container">
    <span class="text-muted">Made by Vinícius.</span>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-custom">
  <b><%= link_to "Anesidora", root_path, class: "navbar-brand" %></b>
  <button class="navbar-toggler custom-toggler" type="button"
                                 data-toggle="collapse"
                                 data-target="#navbarSupportedContent"
                                 aria-controls="navbarSupportedContent"
                                 aria-expanded="false"
                                 aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <big><b><%= link_to "Home", root_path, class:"nav-link space-right" %></b></big>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <big><b><%= link_to "Articles", articles_path, class:"nav-link" %></b></big>
        </li>
        <li class="nav-item">
          <big><b><%= link_to "Users", users_path, class:"nav-link" %></b></big>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <b>
              <p>
                <%= link_to user_path(current_user) do %>
                <svg class="user-icon" width="1em" height="1em"
                     viewBox="0 0 16 16" class="bi bi-person-square"
                     fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                  <path fill-rule="evenodd" d="M2 15v-1c0-1 1-4 6-4s6 3 6 4v1H2zm6-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                </svg>
                <big class="username-color"><b><%= current_user.full_name %></b></big>
                <% end %>
              </p>
            </b>
          </li>
          <li class="nav-item">
            <big><b><%= link_to "Signout", destroy_user_session_path, method: :delete, class:"nav-link space-left" %></b></big>
          </li>
        <% else %>
          <li class="nav-item">
            <big><b><%= link_to "Login", new_user_session_path, class:"nav-link" %></b></big>
          </li>
          <li class="nav-item">
            <big><b><%= link_to "Signup", new_user_registration_path, class:"nav-link" %></b></big>
          </li>
        <% end %>
      </ul>
    </form>
  </div>
</nav>

app/views/shared/_messages.html.erb
<div class="row">
  <div class="col-12 center">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == 'notice' ? 'success' : 'danger' %>" >
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_title.html.erb
<div class="row mspace">
  <div class="center col-12">
    <h1><%= title %></h1>
    <p><%= subtitle %></p>
  </div>
</div>